server:
  servlet:
    context-path: /ai-chat-assistant

app:
  features:
    multi-language-enabled: false  # Toggle this to false to hide language switchers
  volumes:
    - ./logs:/app/logs  # Maps the container's logs to your computer

spring:
  application:
    name: spring-ai-chat-assistant
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: ${SPRING_MONGODB_URI} # Use the variable passed from docker-compose

  # MOVE THIS OUT OF MONGODB
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        project-id: ${GOOGLE_PROJECT_ID}
        chat:
          options:
            model: gemini-2.5-flash

  thymeleaf:
    cache: false
  messages:
    encoding: UTF-8

logging:
  # 1. NEW: Set the log file destination
  file:
    name: logs/spring-ai-chat-assistant.log

  # 2. NEW: Configure auto-cleanup (Rolling Policy)
  logback:
    rollingpolicy:
      max-file-size: 10MB    # Starts a new file after 10MB
      max-history: 7         # Deletes logs older than 7 days
      total-size-cap: 100MB  # Absolute limit for the logs folder

  # 3. Your existing levels
  level:
    root: INFO
    com.nexus.chatassistant: DEBUG
    org.springframework.security: INFO
    org.springframework.ai: INFO