spring:
  application:
    name: spring-ai-chat-assistant
  threads:
    virtual:
      enabled: true
  mongodb:
      uri: mongodb://mongodb:27017/ai_assistant_db
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
  thymeleaf:
    cache: false
  messages:
    encoding: UTF-8

logging:
  level:
    com.nexus.chatassistant: DEBUG
    org.springframework.security: INFO
    org.springframework.ai: INFO
