server:
  servlet:
    context-path: /ai-chat-assistant

spring:
  application:
    name: spring-ai-chat-assistant
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: ${SPRING_MONGODB_URI} # Use the variable passed from docker-compose

  # MOVE THIS OUT OF MONGODB
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        project-id: ${GOOGLE_PROJECT_ID}
        chat:
          options:
            model: gemini-2.5-flash

  thymeleaf:
    cache: false
  messages:
    encoding: UTF-8

logging:
  level:
    com.nexus.chatassistant: DEBUG
    org.springframework.security: INFO
    org.springframework.ai: INFO